import { chromium } from 'playwright';
const base='https://laravel-ms-ai.test', SS='/private/tmp/claude-501/-Users-jasonooi-Herd-laravel-ms-ai/62eb8fcf-eacd-4ef8-a79e-c3db29c26114/scratchpad';
const b=await chromium.launch(); const c=await b.newContext({ignoreHTTPSErrors:true,viewport:{width:1000,height:900}}); const p=await c.newPage();
await p.goto(base+'/demo/login',{waitUntil:'networkidle'});
await p.locator('input[type=email]').fill('admin@gmail.com'); await p.locator('input[type=password]').fill('password123');
await p.getByRole('button',{name:/sign in/i}).click(); await p.waitForURL(/dashboard/,{timeout:25000});
await p.goto(base+'/demo/products',{waitUntil:'networkidle'}); await p.waitForTimeout(500);
await p.locator('table tbody tr').first().getByRole('button').last().click(); await p.waitForTimeout(300);
await p.getByRole('menuitem',{name:/bill of materials/i}).click(); await p.waitForTimeout(700);
await p.locator('[aria-haspopup=listbox]').first().click(); await p.waitForTimeout(500);
console.log('LOG on-open activeEl:', await p.evaluate(()=>{const a=document.activeElement;return a?.tagName+'['+(a?.getAttribute('placeholder')||a?.getAttribute('role')||'')+']';}));
const search = p.getByPlaceholder(/search/i).last();
console.log('LOG search visible:', await search.isVisible().catch(()=>false));
await p.keyboard.type('Ste'); await p.waitForTimeout(400);
console.log('LOG search value after typing:', JSON.stringify(await search.inputValue().catch(()=>'(fail)')));
console.log('LOG popover still open:', await search.isVisible().catch(()=>false), '| option count:', await p.getByRole('option').count());
console.log('LOG options:', JSON.stringify(await p.getByRole('option').allInnerTexts().catch(()=>[])));
await p.screenshot({path:SS+'/combo-fixed.png'});
await b.close();
